// Central input/cost limits. Keep these conservative because every AI request
// can consume paid model capacity.
module.exports = {
  MAX_QUESTION_LEN: 3000,
  MAX_ANSWER_LEN: 2000,
  MAX_ATTEMPT_LEN: 4000,
  MAX_TOPIC_LEN: 200,
  MAX_TOPICS_COUNT: 5,
  MAX_HISTORY_MESSAGES: 60,
  MAX_HISTORY_TEXT_LEN: 4000,
  MAX_GRADE_LABEL_LEN: 100,
  MAX_SUBJECT_LABEL_LEN: 100,
  MAX_DIFFICULTY_LEN: 30,
  MAX_EXAM_ANSWERS: 20,
  MAX_EXAM_TEXT_ANSWER_LEN: 500,
  MAX_EVENT_METADATA_BYTES: 4000,
  MAX_EXTRACTED_TEXT_LEN: 3000,
  MAX_MISTAKE_FIELD_LEN: 1500,
};
