// Server-side persistence for Socratic turns.
// A turnId is generated by the client and reused if the stream is retried.
// This makes the stream and normal endpoint idempotent and keeps the AI reply
// durable even if the browser disconnects after receiving it.
const { admin } = require('./supabaseAdmin');

async function getOwnedSession(db, sessionId, userId) {
  if (typeof sessionId !== 'string' || !sessionId) return null;
  const { data, error } = await db.from('sessions')
    .select('id,user_id,profile_id,subject,subject_label,topic,grade_label')
    .eq('id', sessionId).eq('user_id', userId).maybeSingle();
  if (error || !data) return null;
  return data;
}

async function persistStudentTurn({ sessionId, userId, turnId, content }) {
  const db = admin();
  const owned = await getOwnedSession(db, sessionId, userId);
  if (!owned) return { ok: false, error: 'session_not_owned' };

  if (!content) return { ok: true, session: owned };
  const { data: existing } = await db.from('messages').select('id,role,content')
    .eq('session_id', sessionId).eq('client_turn_id', turnId).eq('role', 'student').maybeSingle();
  if (!existing) {
    const { error } = await db.from('messages').insert({
      user_id: userId, session_id: sessionId, role: 'student',
      content, client_turn_id: turnId
    });
    if (error) return { ok: false, error: error.message };
  }
  return { ok: true, session: owned };
}

async function persistAiTurn({ sessionId, userId, turnId, aiMessage, result }) {
  const db = admin();
  const owned = await getOwnedSession(db, sessionId, userId);
  if (!owned) return { ok: false, error: 'session_not_owned' };

  const { data: existing } = await db.from('messages').select('id,role,content')
    .eq('session_id', sessionId).eq('client_turn_id', turnId).eq('role', 'ai').maybeSingle();
  if (!existing) {
    const { error } = await db.from('messages').insert({
      user_id: userId, session_id: sessionId, role: 'ai',
      content: aiMessage, client_turn_id: turnId
    });
    if (error) return { ok: false, error: error.message };
  }
  if (result?.verdict) {
    // Skill/mistake persistence remains in the browser for now; message
    // durability is the critical SSE boundary. The unique turn key prevents
    // duplicate AI messages when stream -> normal retry happens.
  }
  return { ok: true, session: owned };
}

module.exports = { getOwnedSession, persistStudentTurn, persistAiTurn };
